services:
  ctfd:
    build:
      context: ./
      dockerfile: ./dockerfiles/ctfd.Dockerfile
    user: root
    restart: always
    ports:
      - "8000:8000"
      - "4000:4000"
    env_file:
      - ${ENV_FILE:-.env.prod}   
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - ./backend/ng:/opt/CTFd/CTFd/plugins/ng/:ro
      - /var/lib/certs/ssl/:/var/lib/certs/ssl/
    depends_on:
      - db
      - cache
      - vite
      - nginx
    networks:
      default:
      internal:
    tty: true
    entrypoint : /bin/bash
    command : -c "/usr/bin/supervisord -c /etc/supervisor/supervisord.conf && supervisorctl tail -f ctfd"

  nginx:
    image: nginx:1.28
    restart: always
    volumes:
      - ./conf/nginx/http.prod.conf:/etc/nginx/nginx.conf:ro
      - ./sslpublickey.pem:/certificates/sslpublickey.pem:ro
      - ./privatesslkey.pem:/certificates/privatesslkey.pem:ro
      - ./frontend/dist:/var/www/vite-build:ro
    ports:
      - 80:80
      - 443:443

  db:
    image: mariadb:10.11
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=ctfd
      - MARIADB_USER=ctfd
      - MARIADB_PASSWORD=ctfd
      - MARIADB_DATABASE=ctfd
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
        internal:
        default:
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    restart: always
    volumes:
    - .data/redis:/data
    networks:
        internal:

  vite:
    build:
      context: ./
      dockerfile: ./dockerfiles/vite.Dockerfile
    restart: always
    tty: true
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app/frontend
      - ./node_modules:/app/node_modules

networks:
    default:
    internal:
      internal: true