services:
  ctfd:
    build:
      context: ./
      dockerfile: ./dockerfiles/ctfd.Dockerfile
    container_name: placeholder-ctfd
    user: root
    restart: always
    ports:
      - "8000:8000"
      - "4000:4000"
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - DEBUG=true
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
      - SWAGGER_UI=true
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - ./backend/ctfd/plugin:/opt/CTFd/CTFd/plugins/placeholder/:ro
      - ./backend/ctfd/entrypoint.html:/opt/CTFd/CTFd/themes/core/templates/entrypoint.html:ro
    depends_on:
      - db
    networks:
      default:
      internal:
    entrypoint : /bin/bash
    command : -c "/usr/bin/supervisord -c /etc/supervisor/supervisord.conf && supervisorctl tail -f ctfd"
    profiles : [ full ]

  nginx:
    image: nginx:1.28
    container_name: placeholder-nginx
    restart: always
    volumes:
      - ./conf/nginx/http.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 5173:5173
    depends_on:
      - ctfd
    profiles : [ full ]

  db:
    image: mariadb:10.11
    container_name: placeholder-db
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=ctfd
      - MARIADB_USER=ctfd
      - MARIADB_PASSWORD=ctfd
      - MARIADB_DATABASE=ctfd
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
        internal:
        default:
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]
    profiles : [ full ]

  cache:
    image: redis:4
    container_name: placeholder-redis
    restart: always
    volumes:
    - .data/redis:/data
    networks:
        internal:
    profiles : [ full ]

  vite:
    build:
      context: ./
      dockerfile: ./dockerfiles/vite.Dockerfile
    container_name: placeholder-vite
    restart: always
    tty: true
    volumes:
      - ./frontend:/app
    profiles : [ frontend, full ]

networks:
    default:
    internal:
      internal: true