services: 
  load-test:
    network_mode: "host"
    environment:
      BASE_URL: "http://localhost"
      STAGE_ONE_VUS: 2
      STAGE_TWO_VUS: 5
      STAGE_THREE_VUS: 2
      K6_WEB_DASHBOARD: "true"
      K6_LOG_OUTPUT: "file=output/logging.txt,level=trace"

    cap_add:
      - SYS_ADMIN
    build:
      context: .
    volumes:
      - ./output:/app/output:rw