[pytest]
pythonpath =
    ..
    ../../external/CTFd

testpaths = .

addopts = -p no:warnings --confcutdir=. -ra -v --color=yes
markers =
    db: marks tests as needing database access
    middleware: marks tests as requiring isolated app setup

