[supervisord]
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
user=root

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:ctfd]
command=/opt/CTFd/support-entrypoint.sh 
stdout_logfile=/var/log/supervisor/ctfd.log
stderr_logfile=/var/log/supervisor/ctfd.error.log
autorestart=true
