- name: Sysctl config
  # Replace with inventory conf
  # for docker hosts
  hosts: challenge
  become: true
  # Replace with your remote user
  remote_user: user
  tasks:
    - ansible.posix.sysctl:
        name: kernel.pty.max
        value: '8192'
        state: present
    - ansible.posix.sysctl:
        name: fs.aio-max-nr
        value: '1048576'
        state: present
    - ansible.posix.sysctl:
        name: fs.inotify.max_user_instances
        value: '256'
        state: present

# TODO: this will become part of a larger playbook to provision new challenge hosts