- name: Trigger frontend upload
  hosts: manager

  # github_token: github PAT in semaphore variable group

  tasks:
    - name: Dispatch upload-frontend workflow
      ansible.builtin.uri:
        url: "https://api.github.com/repos/CyberSkyline/ctf-ng/actions/workflows/upload-frontend.yml/dispatches"
        method: POST
        headers:
          Authorization: "Bearer {{ github_token }}"
          Accept: "application/vnd.github+json"
        body_format: json
        body:
          ref: "{{ ctfd_environment }}"
          inputs:
            ref: "{{ ctfd_environment }}"
        status_code: 204
      no_log: true
