name: Deploy to S3

on:
  pull_request:
    branches:
      - development
      - staging
      - production
    types: [closed]

jobs:
  build-and-deploy:
    name: Build and Deploy Vite App
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: yarn install
        working-directory: ./frontend

      - name: Build project
        run: yarn build
        working-directory: ./frontend

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Determine S3 bucket
        id: s3_bucket
        run: |
          if [ "${{ github.base_ref }}" == "development" ]; then echo "bucket=assets.development.ctf-ng" >> $GITHUB_ENV
          elif [ "${{ github.base_ref }}" == "staging" ]; then echo "bucket=assets.staging.ctf-ng" >> $GITHUB_ENV
          elif [ "${{ github.base_ref }}" == "production" ]; then echo "bucket=assets.production.ctf-ng" >> $GITHUB_ENV
          else echo "Unsupported branch: ${{ github.base_ref }}"; exit 1
          fi

      - name: Sync dist to S3 bucket
        run: |
          aws s3 sync ./frontend/dist s3://$bucket --delete
