name: frontend-linter
on:
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-linter.yml'
jobs:
 linter-test:
    name: Linter Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
    - uses: actions/checkout@v4

    - name : Enable Corepack
      run: corepack enable

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install
      run: |
        cd frontend
        pnpm install --ignore-scripts

    - name: Test
      run: |
        cd frontend
        pnpm run lint
      env:
        CI: true
