name: semver
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: staging
          release_strategy: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
