name: semver
on:
  pull_request:
    # types: [closed]

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Tag
        uses: paulhatch/semantic-version@v5.4.0
        with:
          bump_each_commit: true
          bump_each_commit_patch_pattern: "(PATCH)"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
