name: semver
on:
  pull_request:
    # types: [closed]
    branches:
      # - staging

jobs:
  tag:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Tag
        id: tag
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          bump_each_commit: true
          bump_each_commit_patch_pattern: "(PATCH)"

      - name: Create tag
        run: |
          git config --global user.email "zcoughlan@cyberskyline.com"
          git config --global user.name "Zoe Coughlan"
          if git rev-parse "${{ steps.tag.outputs.version_tag }}" >/dev/null 2>&1; then
            echo "Tag ${{ steps.tag.outputs.version_tag }} already exists. Skipping."
          else
            git tag -a "${{ steps.tag.outputs.version_tag }}" -m "version ${{ steps.tag.outputs.version_tag }}"
            git push origin "${{ steps.tag.outputs.version_tag }}"
          fi
      - name: View PR author
        run: echo "This PR is opened by ${{ github.event.pull_request.assignee.name }} with email ${{ github.event.pull_request.assignee.email }}."

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
