name: services-linter
on:
  pull_request:
    paths:
      - 'services/**'
      - '.github/workflows/services-linter.yml'
jobs:
 linter-test:
    name: Linter Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
    - uses: actions/checkout@v7

    - name : Enable Corepack
      run: corepack enable

    - name: Setup pnpm
      uses: pnpm/action-setup@v6
      with:
        run_install: false

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install
      run: |
        cd services/exec-service
        pnpm install --ignore-scripts

    - name: Test
      run: |
        cd services/exec-service
        pnpm run lint
      env:
        CI: true
